# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:month-:year/:title.html

# Setup
title:            Mac Simonson
tagline:          ‘Dartmouth College’
description:      ‘English & Film major, editor for <a href="http://dmouth.com" target="_blank">Mouth Magazine</a> and Telluride Film Festival intern. Tweeting at <a href="https://twitter.com/stackintosh” target="_blank”>@stackintosh</a>.'
url:              http://lanyon.getpoole.com
paginate:         5

author:
  name:           ‘Mac Simonson’
  url:            https://twitter.com/stackintosh

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/macsimonson.github.io
